### ISSUE TITLE
Task 2.0

### ISSUE THREAD

**Issue by JohnKhandygo** [avtuhovich/politech#10]
**Общая формулировка**
Разработать консольную утилиту, реализующую указанную в задании функциональность, на языках Java и/или Kotlin. При проектировании использовать объектно-ориентированный подход. Разработать автоматические тесты для отдельных частей программы. Написанный код держать в отдельном проекте или модуле в репозитории на GitHub.

**шифрация**
Шифрация (-c) или дешифрация (-d) указанного (в аргументе командной строки) файла. Выходной файл указывается как -o filename.txt, по умолчанию имя формируется из имени входного файла с добавлением расширения.
Алгоритм шифрации XOR. Ключ указывается после -c или -d в шестнадцатеричной системе, длина ключа -- любое целое количество байт.

Command Line: ciphxor [-c key] [-d key] inputname.txt [-o outputname.txt]

Кроме самой программы, следует написать автоматические тесты к ней.

Также необходимо разработать скрипты и/или инструкции сборки и запуска разработанного приложения из командной строки. 

**P.S.** Проверка второго задания начинается не раньше исправления всех замечания к первому заданию. В любом случае напишите в комментариях к этому issue, когда задание будет готово к проверке.

**P.S.S.** Если будете делать это задание в другом репозитории, дайте ссылку в комментариях к этому issue.

**Рекомендуется следующий подход к разработке**:
1. Реализовать класс со всей необходимой логикой так, как Вы это делали в предыдущем задании (с покрытием тестами и прочим). Другими словами, забудьте на время, что Ваше приложение должно работать из консоли.
2. Отдельно написать "обертку", которая будет парсить аргументы командной строки (используя библотеку) и вызывать разработанные на первом этапе методы. Скорее всего то, что будет написано на данном этапе даже не потребуется покрывать тестами, поскольку функциональность сторонних библотек обычно не тестируется (либо тестируется в каких-то очень сложных случаях). 

Собственно после готовности первого этапа можно начинать проверку.

**Comment by avtuhovich** [comment]
https://github.com/avtuhovich/Program2 репозиторий для 2 задания

**Comment by JohnKhandygo** [comment]
Перенем описание задания в новый репозиторий. Все замечания будут появляться там.
