### ISSUE TITLE
Upgrade impl.

### ISSUE THREAD

**Issue by JohnKhandygo** [avtuhovich/politech#5]
- [x] По условию задачи необходимо реализовать структуру, близкую к `Set`, а не `Map`.
- [x] Вашу разработку не получится использовать в виде сторонней библиотеки.
- [x] В представленной реализации отсутствует метод сравнения (требуется по условию задачи).

**Comment by JohnKhandygo** [comment]
- [ ] Метод `equals` реализован некорректно.
- [x] Насколько я могу судить, некорректно реализован случай `key = 0`.

**Comment by JohnKhandygo** [comment]
Все, что не отмечено галочкой, актуально.

**Comment by JohnKhandygo** [comment]
Все, что не отмечено галочкой из предыдущих комментариев актуально.
- [x] При объявлении полей и методов принято использовать наиболее "жесткую" возможную область видимости (private > package private > public).
- [x] Если значения полей/переменных не меняется стоит использовать модификатор `final` при их объявлении. Это позволит избежать дурацких ошибок при написании кода. 
- [x] Что такое `degree` в конструкторе `HashTable`? У Вас там, конечно, очень интеллектуальный javadoc написан, но мне все равно не понятно.
- [x] Если `degree = 100`, то произойдет переполнение `int` при вычислении `headNum`. У Вас от этого, наверное, что-то может сломаться.
- [x] Почему `add` принимает boxed тип в качестве аргумента?
- [ ] Метод `add` не предоставляет возможности программно определить, было ли на самом деле совершено добавление элемента или такой уже был в множестве.
- [x] Для чего Вам метод `get`?
- [x] Почему `remove` принимает boxed тип в качестве аргумента?
- [x] Если Вы бросаете  исключение, то следует давать ему описание (на английском языке).

**Comment by avtuhovich** [comment]
Исправила ошибки в коде

**Comment by JohnKhandygo** [comment]
Все, что не отмечено галочкой в предыдущих комментариях актуально.

> Метод `equals` реализован некорректно.

Возможно я чего-то не понимаю. Если считаете текущую реализацию правильной, объясните почему.

> Что такое `degree` в конструкторе `HashTable`? У Вас там, конечно, очень интеллектуальный javadoc написан, но мне все равно не понятно.

Будем считать, что это теперь касается параметра `headCount`. Меня интересует семантическое значение этого параметра. Что-то вроде "размер массива `head`" не канает.

**Comment by avtuhovich** [comment]
headCount - количество элементов массива, которые хранят ссылки на мультисписки с элементами
