### ISSUE TITLE
Corrections

### ISSUE THREAD

**Issue by JohnKhandygo** [avtuhovich/politech#9]
Как-то туго у Вас идет. До сих пор куча ошибок в реализации, тесты нормальные Вы писать не хотите. Предлагаю следующие варианты:
1. Пытаетесь и дальше закрыть все замечания. Скорее всего не успеете сделать все задания. 
2. Закрываете только те замечания, которые касаются тестов и реализации, получаете оценку 3.5 (4 - 0.5 штрафных баллов за первую аттестацию) и следующее задание. 
3. Получаете минимальную положительную оценку (2.5) за это задание прямо сейчас и следующее задание сразу же.

Напишите в комментариях, какой вариант выбираете. Либо можно на паре обсудить.

**Comment by avtuhovich** [comment]
33

**Comment by JohnKhandygo** [comment]
Окей. Второе задание в отдельном issue.
